"""Exact, inspectable filesystem materialization of corpus rendered text.

The generated .ignore fixes ripgrep visibility beneath ignored plugin data
directories. It is not an isolation boundary: official tool glob overrides can
ignore its file exclusions, so the on-disk inventory must also be exact.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path, PurePosixPath
from typing import Any


_IGNORE_HEADER = "# Generated by dsh_plugin.backend.corpus_workspace\n"


def _documents(corpus: list[dict[str, Any]]) -> dict[str, bytes]:
    if not corpus:
        raise ValueError("corpus must contain at least one document")
    documents: dict[str, bytes] = {}
    for row in corpus:
        source_path = row.get("source_path")
        if not isinstance(source_path, str) or not source_path:
            raise ValueError("corpus source_path must be a non-empty string")
        relative = PurePosixPath(source_path)
        if (
            not relative.parts
            or relative.is_absolute()
            or ".." in relative.parts
            or source_path != relative.as_posix()
            or any(ord(character) < 32 for character in source_path)
            or any(part.casefold() in {".ignore", ".git"} for part in relative.parts)
        ):
            raise ValueError(f"unsafe corpus source_path: {source_path!r}")
        if source_path in documents:
            raise ValueError(f"duplicate corpus source_path: {source_path!r}")
        rendered_text = row.get("rendered_text")
        if not isinstance(rendered_text, str):
            raise ValueError(f"corpus rendered_text must be a string: {source_path!r}")
        documents[source_path] = rendered_text.encode("utf-8")
    collisions = set(documents) & _directories(documents)
    if collisions:
        raise ValueError(f"corpus file/directory collision: {sorted(collisions)!r}")
    # The supported local runner can live on a case-insensitive filesystem.
    # Reject aliases before writing rather than silently replacing either path.
    spellings: dict[str, str] = {}
    for path in set(documents) | _directories(documents):
        previous = spellings.setdefault(path.casefold(), path)
        if previous != path:
            raise ValueError(f"case-insensitive corpus path collision: {previous!r}, {path!r}")
    return documents


def _directories(documents: dict[str, bytes]) -> set[str]:
    return {
        parent.as_posix()
        for path in documents
        for parent in PurePosixPath(path).parents
        if parent != PurePosixPath(".")
    }


def _ignore_text(documents: dict[str, bytes]) -> bytes:
    def escape(path: str) -> str:
        # Gitignore patterns, not shell patterns: anchor each literal path and
        # escape wildcard metacharacters, backslashes, and significant spaces.
        return "".join("\\" + char if char in "\\*?[]#! " else char for char in path)

    directories = sorted(
        _directories(documents), key=lambda path: (path.count("/"), path)
    )
    lines = ["*", "!/.ignore"]
    lines.extend(f"!/{escape(path)}/" for path in directories)
    lines.extend(f"!/{escape(path)}" for path in sorted(documents))
    return (_IGNORE_HEADER + "\n".join(lines) + "\n").encode("utf-8")


def _inventory(destination: Path, documents: dict[str, bytes]) -> set[str]:
    # Check the lexical path before resolving so a root/ancestor symlink cannot
    # silently redirect preparation or preflight to another workspace.
    for path in (destination, *destination.parents):
        if path.is_symlink():
            raise ValueError(f"symlink in corpus workspace path: {path}")
        if path.exists() and not path.is_dir():
            raise ValueError(f"corpus workspace path is not a directory: {path}")
    if not destination.exists():
        return set()
    expected_files = set(documents) | {".ignore"}
    expected_directories = _directories(documents)
    files: set[str] = set()

    def visit(directory: Path) -> None:
        for path in sorted(directory.iterdir()):
            relative = path.relative_to(destination).as_posix()
            if path.is_symlink():
                raise ValueError(f"symlink in corpus workspace: {relative}")
            if path.is_dir():
                if relative not in expected_directories:
                    raise ValueError(f"extra directory in corpus workspace: {relative}")
                visit(path)
            elif path.is_file():
                if relative not in expected_files:
                    raise ValueError(f"extra file in corpus workspace: {relative}")
                files.add(relative)
            else:
                raise ValueError(f"non-regular entry in corpus workspace: {relative}")

    visit(destination)
    return files


def _digest(files: dict[str, bytes]) -> str:
    entries = [
        [path, hashlib.sha256(content).hexdigest()]
        for path, content in sorted(files.items())
    ]
    return hashlib.sha256(
        json.dumps(entries, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
    ).hexdigest()


def validate_corpus_workspace(
    corpus: list[dict[str, Any]], destination: Path
) -> dict[str, Any]:
    """Reject any inventory/content drift; return deterministic snapshot hashes.

    ``corpus_sha256`` hashes sorted [source_path, rendered_text SHA-256] pairs;
    ``workspace_sha256`` additionally includes the generated root .ignore.
    This is a point-in-time validation, not a filesystem access sandbox.
    """
    documents = _documents(corpus)
    destination = Path(destination).expanduser().absolute()
    expected = {**documents, ".ignore": _ignore_text(documents)}
    actual_paths = _inventory(destination, documents)
    missing = set(expected) - actual_paths
    if missing:
        raise ValueError(f"missing files in corpus workspace: {sorted(missing)!r}")
    for relative, content in expected.items():
        if destination.joinpath(*PurePosixPath(relative).parts).read_bytes() != content:
            raise ValueError(f"content mismatch in corpus workspace: {relative}")
    return {
        "documents": str(destination.resolve()),
        "document_count": len(documents),
        "corpus_sha256": _digest(documents),
        "workspace_sha256": _digest(expected),
        "ignore_sha256": hashlib.sha256(expected[".ignore"]).hexdigest(),
    }


def materialize_corpus_workspace(
    corpus: list[dict[str, Any]], destination: Path
) -> dict[str, Any]:
    """Write rendered_text only, refusing stale extras or redirected targets.

    Existing manifest document paths may be refreshed. Extra files/directories
    are never deleted: callers must select a clean destination or explicitly
    move stale data themselves before trying again.
    """
    documents = _documents(corpus)
    destination = Path(destination).expanduser().absolute()
    files = _inventory(destination, documents)
    if ".ignore" in files and not (destination / ".ignore").read_bytes().startswith(
        _IGNORE_HEADER.encode("utf-8")
    ):
        raise ValueError("refusing to overwrite an unmanaged corpus workspace .ignore")
    destination.mkdir(parents=True, exist_ok=True)
    for relative, content in {**documents, ".ignore": _ignore_text(documents)}.items():
        target = destination.joinpath(*PurePosixPath(relative).parts)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(content)
    return validate_corpus_workspace(corpus, destination)
